### ISSUE TITLE
Error in STACK_DTOR

### ISSUE THREAD

**Issue by Alexandr26Starostin** [TolikRogov/StackForHacking#1]
> [!IMPORTANT]
> Hello! 
>
>I find error in your stack: branch - main.

## **Where is the problem ?**

> [!WARNING]
>Problem in DoStackDtor. If it give pointer == NULL, func don't check it. 
>
## **Your define that use in main and call DoStackDtor:**
```
#define STACK_DTOR(stk) {                                                       \
	StackStatusCode status = DoStackDtor(stk);						        \
	STACK_ERROR_CHECK(status, stk);									\
}
```
>
## **Your func:**
```
StackStatusCode DoStackDtor(Stack_t* stk) {

#ifdef HASH_PROTECTION
	stk->hash      = (Hash_t)TRASH;
	stk->data_hash = (Hash_t)TRASH;
#endif

#ifdef CANARY_PROTECTION
	stk->canary1 = (Canary_t)TRASH;
	stk->canary2 = (Canary_t)TRASH;
#endif

	stk->capacity = TRASH;
	stk->size         = TRASH;

	if (stk->data) {

#ifdef CANARY_PROTECTION
		char* alloc_memory = ((char*)stk->data - sizeof(Canary_t));
#else
		char* alloc_memory = (char*)stk->data;
#endif

		free(alloc_memory);
		alloc_memory = NULL;

#ifdef N_DEBUG
		printf("\n\n" GREEN("ALLOCATED MEMORY FREED") "\n\n");
#endif

	}
```

## **Example code that breaks the program**
```
int main() {
	INIT_STACK(stk);

	STACK_CTOR(&stk, 16);

	for (Stack_elem_t i = 0; i < 20; i++)
		STACK_PUSH(&stk, 10);

	Stack_elem_t x = 0;
	for (Stack_elem_t i = 0; i < 20; i++)
		
		STACK_POP(&stk, &x);

	STACK_DTOR(NULL);

	return 0;
}

```

> [!CAUTION]
>Print in console:
```
==5639==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x5de6e077dc9a bp 0x7ffd0d79fe20 sp 0x7ffd0d79fd40 T0)
==5639==The signal is caused by a WRITE memory access.
==5639==Hint: address points to the zero page.
    #0 0x5de6e077dc9a in DoStackDtor(Stack_t*) source/stack.cpp:256
    #1 0x5de6e077a1c0 in main source/main.cpp:31
    #2 0x79beb8034e07  (/usr/lib/libc.so.6+0x25e07) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #3 0x79beb8034ecb in __libc_start_main (/usr/lib/libc.so.6+0x25ecb) (BuildId: 98b3d8e0b8c534c769cb871c438b4f8f3a8e4bf3)
    #4 0x5de6e0779204 in _start (/home/sasha/Desktop/stack_fix/build/st+0xc204) (BuildId: b37ec3ce2b4ebaebc6c38c42fa09e879f42fc904)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV source/stack.cpp:256 in DoStackDtor(Stack_t*)
==5639==ABORTING
```

> [!TIP]
>I think, you can add assert or if for checking meaning of pointer in func DoStackDtor. It solves the problem.

**Comment by TolikRogov** [comment]
Hello! 
Thank you for your attentiveness and willingness to help! The bug has been fixed, if you use my project, see the "Stack" repository in the future:)
